### ISSUE TITLE
Support null-safety

### ISSUE THREAD

**Issue by TimWhiting** [Workiva/dart_codemod#37]
Looks like the only non dev-dependency that doesn't support null safety yet is `package:io`, which now has an open [PR](https://github.com/dart-lang/io/pull/67) for null safety.

**Comment by evanweible-wf** [comment]
Thanks for the issue! I'll keep an eye on that `package:io` PR and get started on one for this repo.

**Comment by rvowles** [comment]
It has merged now if thats of any interest.

**Comment by evanweible-wf** [comment]
Thanks @rvowles! Put up a null-safety PR here: #43
